import { Order, OrderItem, OrderStatus, OrderStatusHistory, ShippingAddress } from './types';

// ============================================================================
// MOCK ORDERS DATA
// ============================================================================

export const mockOrders: Order[] = [
    {
        id: 'ORD-001',
        orderNumber: 'ORD-MON-000001',
        customerName: 'Jean Dupont',
        customerEmail: 'jean.dupont@example.com',
        customerPhone: '+1 514 555 0101',
        shippingAddress: {
            street: '123 Rue Principale',
            city: 'Montréal',
            state: 'QC',
            zip: 'H3Z 2Y7',
            country: 'CA',
        },
        items: [
            {
                id: 'item-1',
                productId: '1',
                name: 'Tennis Urban Runner',
                quantity: 1,
                price: 89.99,
                size: '42',
                image: '/products/tennis-urban-1.jpg',
            },
            {
                id: 'item-2',
                productId: '2',
                name: 'Chemise Oxford Blue',
                quantity: 2,
                price: 45.00,
                size: 'L',
                image: '/products/shirt-oxford-1.jpg',
            },
        ],
        status: 'pending',
        statusHistory: [
            { status: 'pending', timestamp: '2025-11-24T10:30:00Z', note: 'Commande reçue' },
        ],
        subtotal: 179.99,
        shippingCost: 12.50,
        tax: 23.40,
        total: 215.89,
        currency: 'CAD',
        date: '2025-11-24T10:30:00Z',
        paymentMethod: 'Square (Visa **** 4242)',
        internalNotes: 'Client régulier - Priorité haute',
    },
    {
        id: 'ORD-002',
        orderNumber: 'ORD-MON-000002',
        customerName: 'Alice Smith',
        customerEmail: 'alice.smith@example.com',
        customerPhone: '+1 212 555 0199',
        shippingAddress: {
            street: '456 Broadway',
            city: 'New York',
            state: 'NY',
            zip: '10012',
            country: 'US',
        },
        items: [
            {
                id: 'item-3',
                productId: '3',
                name: 'Jeans Slim Fit Indigo',
                quantity: 1,
                price: 59.50,
                size: '32',
                image: '/products/jeans-slim-1.jpg',
            },
        ],
        status: 'shipped',
        statusHistory: [
            { status: 'pending', timestamp: '2025-11-23T14:15:00Z', note: 'Commande reçue' },
            { status: 'processing', timestamp: '2025-11-23T15:00:00Z', note: 'En préparation', updatedBy: 'SA-001' },
            { status: 'shipped', timestamp: '2025-11-24T09:00:00Z', note: 'Expédié via USPS', updatedBy: 'admin' },
        ],
        subtotal: 59.50,
        shippingCost: 8.99,
        tax: 5.95,
        total: 74.44,
        currency: 'USD',
        date: '2025-11-23T14:15:00Z',
        trackingNumber: 'USPS9400100000000000000001',
        paymentMethod: 'Square (Mastercard **** 5555)',
    },
    {
        id: 'ORD-003',
        orderNumber: 'ORD-MON-000003',
        customerName: 'Carlos Rodriguez',
        customerEmail: 'carlos.r@example.com',
        customerPhone: '+52 55 1234 5678',
        shippingAddress: {
            street: 'Av. Reforma 789',
            city: 'Ciudad de México',
            state: 'CDMX',
            zip: '06600',
            country: 'MX',
        },
        items: [
            {
                id: 'item-4',
                productId: '5',
                name: 'Baskets Running Pro',
                quantity: 1,
                price: 119.99,
                size: '42',
                image: '/products/running-pro-1.jpg',
            },
            {
                id: 'item-5',
                productId: '4',
                name: 'Maillot Sport Pro',
                quantity: 2,
                price: 29.99,
                size: 'L',
                image: '/products/jersey-pro-1.jpg',
            },
        ],
        status: 'processing',
        statusHistory: [
            { status: 'pending', timestamp: '2025-11-24T08:00:00Z', note: 'Commande reçue' },
            { status: 'processing', timestamp: '2025-11-24T10:15:00Z', note: 'En préparation', updatedBy: 'SA-002' },
        ],
        subtotal: 179.97,
        shippingCost: 25.00,
        tax: 32.79,
        total: 237.76,
        currency: 'MXN',
        date: '2025-11-24T08:00:00Z',
        paymentMethod: 'Square (Visa **** 1234)',
        internalNotes: 'Première commande - Vérifier adresse',
    },
    {
        id: 'ORD-004',
        orderNumber: 'ORD-MON-000004',
        customerName: 'Marie Martin',
        customerEmail: 'marie.martin@example.com',
        customerPhone: '+1 514 555 0202',
        shippingAddress: {
            street: '789 Rue Saint-Denis',
            city: 'Montréal',
            state: 'QC',
            zip: 'H2X 3L4',
            country: 'CA',
        },
        items: [
            {
                id: 'item-6',
                productId: '6',
                name: 'Chemise Lin Blanc',
                quantity: 1,
                price: 52.00,
                size: 'M',
                image: '/products/linen-white-1.jpg',
            },
            {
                id: 'item-7',
                productId: '9',
                name: 'Sneakers Classic White',
                quantity: 1,
                price: 79.99,
                size: '40',
                image: '/products/sneaker-white-1.jpg',
            },
        ],
        status: 'delivered',
        statusHistory: [
            { status: 'pending', timestamp: '2025-11-20T11:00:00Z', note: 'Commande reçue' },
            { status: 'processing', timestamp: '2025-11-20T14:00:00Z', note: 'En préparation', updatedBy: 'SA-001' },
            { status: 'shipped', timestamp: '2025-11-21T09:00:00Z', note: 'Expédié', updatedBy: 'admin' },
            { status: 'delivered', timestamp: '2025-11-23T15:30:00Z', note: 'Livré avec succès' },
        ],
        subtotal: 131.99,
        shippingCost: 10.00,
        tax: 18.48,
        total: 160.47,
        currency: 'CAD',
        date: '2025-11-20T11:00:00Z',
        trackingNumber: 'CP1234567890CA',
        paymentMethod: 'Square (Amex **** 9876)',
    },
    {
        id: 'ORD-005',
        orderNumber: 'ORD-MON-000005',
        customerName: 'John Williams',
        customerEmail: 'john.w@example.com',
        customerPhone: '+1 415 555 0303',
        shippingAddress: {
            street: '321 Market Street',
            city: 'San Francisco',
            state: 'CA',
            zip: '94102',
            country: 'US',
        },
        items: [
            {
                id: 'item-8',
                productId: '7',
                name: 'Jean Cargo Noir',
                quantity: 1,
                price: 69.99,
                size: '34',
                image: '/products/cargo-black-1.jpg',
            },
        ],
        status: 'pending',
        statusHistory: [
            { status: 'pending', timestamp: '2025-11-24T16:45:00Z', note: 'Commande reçue' },
        ],
        subtotal: 69.99,
        shippingCost: 9.99,
        tax: 7.00,
        total: 86.98,
        currency: 'USD',
        date: '2025-11-24T16:45:00Z',
        paymentMethod: 'Square (Visa **** 7890)',
    },
    {
        id: 'ORD-006',
        orderNumber: 'ORD-MON-000006',
        customerName: 'Sophie Tremblay',
        customerEmail: 'sophie.t@example.com',
        customerPhone: '+1 418 555 0404',
        shippingAddress: {
            street: '456 Grande Allée',
            city: 'Québec',
            state: 'QC',
            zip: 'G1R 2J5',
            country: 'CA',
        },
        items: [
            {
                id: 'item-9',
                productId: '8',
                name: 'T-Shirt Performance',
                quantity: 3,
                price: 24.99,
                size: 'M',
                image: '/products/tshirt-perf-1.jpg',
            },
            {
                id: 'item-10',
                productId: '4',
                name: 'Maillot Sport Pro',
                quantity: 1,
                price: 29.99,
                size: 'M',
                image: '/products/jersey-pro-1.jpg',
            },
        ],
        status: 'processing',
        statusHistory: [
            { status: 'pending', timestamp: '2025-11-24T12:00:00Z', note: 'Commande reçue' },
            { status: 'processing', timestamp: '2025-11-24T13:30:00Z', note: 'En préparation', updatedBy: 'SA-003' },
        ],
        subtotal: 104.96,
        shippingCost: 11.50,
        tax: 15.17,
        total: 131.63,
        currency: 'CAD',
        date: '2025-11-24T12:00:00Z',
        paymentMethod: 'Square (Mastercard **** 3456)',
        internalNotes: 'Commande groupée - Emballer ensemble',
    },
    {
        id: 'ORD-007',
        orderNumber: 'ORD-MON-000007',
        customerName: 'Miguel Hernandez',
        customerEmail: 'miguel.h@example.com',
        customerPhone: '+52 33 9876 5432',
        shippingAddress: {
            street: 'Calle Juárez 234',
            city: 'Guadalajara',
            state: 'JAL',
            zip: '44100',
            country: 'MX',
        },
        items: [
            {
                id: 'item-11',
                productId: '1',
                name: 'Tennis Urban Runner',
                quantity: 2,
                price: 89.99,
                size: '43',
                image: '/products/tennis-urban-1.jpg',
            },
        ],
        status: 'shipped',
        statusHistory: [
            { status: 'pending', timestamp: '2025-11-22T09:00:00Z', note: 'Commande reçue' },
            { status: 'processing', timestamp: '2025-11-22T11:00:00Z', note: 'En préparation', updatedBy: 'SA-002' },
            { status: 'shipped', timestamp: '2025-11-23T10:00:00Z', note: 'Expédié', updatedBy: 'admin' },
        ],
        subtotal: 179.98,
        shippingCost: 30.00,
        tax: 33.60,
        total: 243.58,
        currency: 'MXN',
        date: '2025-11-22T09:00:00Z',
        trackingNumber: 'MX9876543210',
        paymentMethod: 'Square (Visa **** 5678)',
    },
    {
        id: 'ORD-008',
        orderNumber: 'ORD-MON-000008',
        customerName: 'Emily Johnson',
        customerEmail: 'emily.j@example.com',
        customerPhone: '+1 305 555 0505',
        shippingAddress: {
            street: '789 Ocean Drive',
            city: 'Miami',
            state: 'FL',
            zip: '33139',
            country: 'US',
        },
        items: [
            {
                id: 'item-12',
                productId: '10',
                name: 'Chemise Carreaux Rouge',
                quantity: 1,
                price: 48.00,
                size: 'S',
                image: '/products/plaid-red-1.jpg',
            },
            {
                id: 'item-13',
                productId: '3',
                name: 'Jeans Slim Fit Indigo',
                quantity: 1,
                price: 59.50,
                size: '30',
                image: '/products/jeans-slim-1.jpg',
            },
        ],
        status: 'delivered',
        statusHistory: [
            { status: 'pending', timestamp: '2025-11-19T10:00:00Z', note: 'Commande reçue' },
            { status: 'processing', timestamp: '2025-11-19T12:00:00Z', note: 'En préparation', updatedBy: 'SA-001' },
            { status: 'shipped', timestamp: '2025-11-20T08:00:00Z', note: 'Expédié', updatedBy: 'admin' },
            { status: 'delivered', timestamp: '2025-11-22T14:00:00Z', note: 'Livré' },
        ],
        subtotal: 107.50,
        shippingCost: 8.99,
        tax: 9.67,
        total: 126.16,
        currency: 'USD',
        date: '2025-11-19T10:00:00Z',
        trackingNumber: 'USPS9400100000000000000002',
        paymentMethod: 'Square (Visa **** 2468)',
    },
    {
        id: 'ORD-009',
        orderNumber: 'ORD-MON-000009',
        customerName: 'Pierre Dubois',
        customerEmail: 'pierre.d@example.com',
        customerPhone: '+1 514 555 0606',
        shippingAddress: {
            street: '234 Rue Sherbrooke',
            city: 'Montréal',
            state: 'QC',
            zip: 'H3A 1B4',
            country: 'CA',
        },
        items: [
            {
                id: 'item-14',
                productId: '5',
                name: 'Baskets Running Pro',
                quantity: 1,
                price: 119.99,
                size: '44',
                image: '/products/running-pro-1.jpg',
            },
        ],
        status: 'cancelled',
        statusHistory: [
            { status: 'pending', timestamp: '2025-11-23T15:00:00Z', note: 'Commande reçue' },
            { status: 'cancelled', timestamp: '2025-11-23T16:30:00Z', note: 'Annulée par le client' },
        ],
        subtotal: 119.99,
        shippingCost: 12.50,
        tax: 17.22,
        total: 149.71,
        currency: 'CAD',
        date: '2025-11-23T15:00:00Z',
        paymentMethod: 'Square (Visa **** 1357) - Remboursé',
        internalNotes: 'Client a changé d\'avis - Remboursement effectué',
    },
    {
        id: 'ORD-010',
        orderNumber: 'ORD-MON-000010',
        customerName: 'Laura Garcia',
        customerEmail: 'laura.g@example.com',
        customerPhone: '+52 81 5555 7890',
        shippingAddress: {
            street: 'Av. Constitución 567',
            city: 'Monterrey',
            state: 'NL',
            zip: '64000',
            country: 'MX',
        },
        items: [
            {
                id: 'item-15',
                productId: '2',
                name: 'Chemise Oxford Blue',
                quantity: 1,
                price: 45.00,
                size: 'M',
                image: '/products/shirt-oxford-1.jpg',
            },
            {
                id: 'item-16',
                productId: '6',
                name: 'Chemise Lin Blanc',
                quantity: 1,
                price: 52.00,
                size: 'M',
                image: '/products/linen-white-1.jpg',
            },
        ],
        status: 'pending',
        statusHistory: [
            { status: 'pending', timestamp: '2025-11-24T18:00:00Z', note: 'Commande reçue' },
        ],
        subtotal: 97.00,
        shippingCost: 22.00,
        tax: 19.04,
        total: 138.04,
        currency: 'MXN',
        date: '2025-11-24T18:00:00Z',
        paymentMethod: 'Square (Mastercard **** 8642)',
    },
    {
        id: 'ORD-011',
        orderNumber: 'ORD-MON-000011',
        customerName: 'David Lee',
        customerEmail: 'david.l@example.com',
        customerPhone: '+1 206 555 0707',
        shippingAddress: {
            street: '890 Pine Street',
            city: 'Seattle',
            state: 'WA',
            zip: '98101',
            country: 'US',
        },
        items: [
            {
                id: 'item-17',
                productId: '9',
                name: 'Sneakers Classic White',
                quantity: 2,
                price: 79.99,
                size: '42',
                image: '/products/sneaker-white-1.jpg',
            },
            {
                id: 'item-18',
                productId: '8',
                name: 'T-Shirt Performance',
                quantity: 2,
                price: 24.99,
                size: 'L',
                image: '/products/tshirt-perf-1.jpg',
            },
        ],
        status: 'processing',
        statusHistory: [
            { status: 'pending', timestamp: '2025-11-24T14:00:00Z', note: 'Commande reçue' },
            { status: 'processing', timestamp: '2025-11-24T15:30:00Z', note: 'En préparation', updatedBy: 'SA-001' },
        ],
        subtotal: 209.96,
        shippingCost: 12.99,
        tax: 18.90,
        total: 241.85,
        currency: 'USD',
        date: '2025-11-24T14:00:00Z',
        paymentMethod: 'Square (Amex **** 9753)',
        internalNotes: 'Commande importante - Priorité',
    },
    {
        id: 'ORD-012',
        orderNumber: 'ORD-MON-000012',
        customerName: 'Isabelle Gagnon',
        customerEmail: 'isabelle.g@example.com',
        customerPhone: '+1 819 555 0808',
        shippingAddress: {
            street: '567 Rue Wellington',
            city: 'Gatineau',
            state: 'QC',
            zip: 'J8X 3Y2',
            country: 'CA',
        },
        items: [
            {
                id: 'item-19',
                productId: '7',
                name: 'Jean Cargo Noir',
                quantity: 1,
                price: 69.99,
                size: '32',
                image: '/products/cargo-black-1.jpg',
            },
            {
                id: 'item-20',
                productId: '10',
                name: 'Chemise Carreaux Rouge',
                quantity: 1,
                price: 48.00,
                size: 'L',
                image: '/products/plaid-red-1.jpg',
            },
        ],
        status: 'shipped',
        statusHistory: [
            { status: 'pending', timestamp: '2025-11-21T10:00:00Z', note: 'Commande reçue' },
            { status: 'processing', timestamp: '2025-11-21T13:00:00Z', note: 'En préparation', updatedBy: 'SA-003' },
            { status: 'shipped', timestamp: '2025-11-22T09:00:00Z', note: 'Expédié', updatedBy: 'admin' },
        ],
        subtotal: 117.99,
        shippingCost: 11.00,
        tax: 16.77,
        total: 145.76,
        currency: 'CAD',
        date: '2025-11-21T10:00:00Z',
        trackingNumber: 'CP0987654321CA',
        paymentMethod: 'Square (Visa **** 1122)',
    },
];

// Helper functions
export function getOrderById(id: string): Order | undefined {
    return mockOrders.find(o => o.id === id);
}

export function getOrdersByStatus(status: OrderStatus): Order[] {
    return mockOrders.filter(o => o.status === status);
}

export function getOrdersByCountry(country: 'US' | 'CA' | 'MX'): Order[] {
    return mockOrders.filter(o => o.shippingAddress.country === country);
}

export function getPendingOrders(): Order[] {
    return mockOrders.filter(o => o.status === 'pending' || o.status === 'processing');
}

// For backward compatibility
export type { OrderStatus, OrderItem, Order };
